DROP TABLE IF EXISTS RESOURCES;
CREATE TABLE RESOURCES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);
INSERT INTO RESOURCES (NAME) VALUES('Doctor appointment');
INSERT INTO RESOURCES (NAME) VALUES('Delivery of goods');
SELECT * FROM RESOURCES;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50)
);
INSERT INTO USERS (NAME) VALUES('Artem');
INSERT INTO USERS (NAME) VALUES('Nikita');
SELECT * FROM USERS;

DROP TABLE IF EXISTS USER_RESOURCES;
CREATE TABLE USER_RESOURCES (
    USER_ID INT,
    RESOURCE_ID INT,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY(RESOURCE_ID) REFERENCES RESOURCES(ID)
);
INSERT INTO USER_RESOURCES(
    USER_ID,
    RESOURCE_ID
) VALUES (
    (SELECT ID FROM USERS WHERE NAME='Nikita'),
    (SELECT ID FROM RESOURCES WHERE NAME='Doctor appointment')
);
SELECT * FROM USER_RESOURCES;

DROP TABLE IF EXISTS RESOURCE_RESERVE;
CREATE TABLE RESOURCE_RESERVE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RESERVE_START TIMESTAMP,
    RESERVE_END TIMESTAMP,
    RESOURCE_ID INT,
    USER_ID INT,
    FOREIGN KEY(RESOURCE_ID) REFERENCES RESOURCES(ID),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);
INSERT INTO RESOURCE_RESERVE (
    RESERVE_START,
    RESERVE_END,
    RESOURCE_ID,
    USER_ID
) VALUES (
    {ts '2012-09-17 18:47:52'},
    {ts '2012-09-17 18:47:57'},
    (SELECT ID FROM RESOURCES WHERE NAME='Doctor appointment'),
    (SELECT ID FROM USERS WHERE NAME='Nikita')
);
SELECT * FROM RESOURCE_RESERVE;